/**
 * @enterprise/heartbeat-familiard
 *
 * Adapter that connects Familiard's escalation system to the Enterprise daemon.
 *
 * Two directions:
 *
 * 1. INBOUND: Familiard escalates → Enterprise receives via HTTP webhook
 *    - Add an endpoint to Enterprise API that Familiard POSTs to
 *    - Escalations become high-priority messages in the daemon queue
 *
 * 2. OUTBOUND: Enterprise configures Familiard watchers
 *    - Generate familiard config.yaml from Enterprise settings
 *    - Manage watcher lifecycle (start/stop/status)
 *
 * The key insight: Familiard runs LOCALLY (cheap, Ollama) and only escalates
 * to the Enterprise daemon (expensive, Claude Max) when something needs real thinking.
 */

// ─── Types matching Familiard's escalation payload ───

export type Classification = 'ignore' | 'log' | 'escalate';

export interface ClassifiedEvent {
  eventId: string;
  classification: Classification;
  confidence: number;
  reason: string;
  escalationSummary?: string;
}

export interface JournalEntry {
  timestamp: Date;
  source: string;
  type: string;
  summary: string;
  classification: Classification;
  reason: string;
}

export interface EscalationPayload {
  source: 'familiard';
  timestamp: string;
  events: Array<{
    eventId: string;
    classification: string;
    reason: string;
    summary: string;
    confidence: number;
  }>;
  context: string | null;
}

// ─── Inbound: receive escalations ───

export interface EscalationMessage {
  threadId: string;
  content: string;
  priority: 'high' | 'normal';
  source: 'familiard';
  events: EscalationPayload['events'];
}

/**
 * Parse a Familiard HTTP escalation payload into an Enterprise message.
 */
export function parseEscalation(payload: EscalationPayload, threadId: string): EscalationMessage {
  const summaries = payload.events
    .map((e) => `• ${e.summary}`)
    .join('\n');

  const content = `🔴 Familiard Escalation\n\n${summaries}${
    payload.context ? `\n\nRecent activity:\n${payload.context}` : ''
  }\n\nPlease analyze and respond.`;

  return {
    threadId,
    content,
    priority: 'high',
    source: 'familiard',
    events: payload.events,
  };
}

// ─── Outbound: generate Familiard config ───

export interface FamiliardWatcherConfig {
  type: 'filesystem' | 'git' | 'http' | 'email';
  name: string;
  options: Record<string, unknown>;
}

export interface EnterpriseFamiliardConfig {
  /** Ollama model for local classification */
  model?: string;
  /** Seconds between classification ticks */
  tickInterval?: number;
  /** Watchers to configure */
  watchers: FamiliardWatcherConfig[];
  /** Enterprise API URL for escalation */
  enterpriseUrl: string;
  /** Optional: dedicated thread for escalations */
  escalationThreadId?: string;
  /** Confidence threshold (below = auto-escalate) */
  confidenceThreshold?: number;
}

/**
 * Generate a Familiard config.yaml from Enterprise settings.
 */
export function generateFamiliardConfig(config: EnterpriseFamiliardConfig): string {
  const watchers = config.watchers.map((w) => {
    const opts = Object.entries(w.options)
      .map(([k, v]) => `    ${k}: ${typeof v === 'string' ? `"${v}"` : v}`)
      .join('\n');
    return `  - type: ${w.type}\n    name: ${w.name}\n${opts}`;
  }).join('\n');

  return `# Generated by Enterprise — do not edit manually
model: ${config.model || 'llama3.1:8b-instruct'}
tick_interval: ${config.tickInterval || 60}
confidence_threshold: ${config.confidenceThreshold || 0.6}

watchers:
${watchers}

escalation:
  method: http
  url: ${config.enterpriseUrl}/api/familiard/escalate
  headers:
    Content-Type: "application/json"
  contextWindow: 10

journal:
  dir: ~/.familiard/journal
`;
}

// ─── Hono route factory ───

/**
 * Returns Hono route handlers for the Enterprise API.
 * Wire these into your Hono app:
 *
 *   const familiard = createFamiliardRoutes(db, config);
 *   app.post('/api/familiard/escalate', familiard.escalate);
 *   app.get('/api/familiard/config', familiard.getConfig);
 *   app.get('/api/familiard/status', familiard.getStatus);
 */
export function createFamiliardRoutes(deps: {
  /** Insert a message into the Enterprise queue */
  insertMessage: (threadId: string, role: string, content: string, status: string, metadata: string | null) => void;
  /** Ensure a thread exists, return its ID */
  ensureThread: (id: string, title: string) => string;
  /** Current config */
  config: EnterpriseFamiliardConfig;
}) {
  const ESCALATION_THREAD_TITLE = '🔴 Familiard Escalations';

  let lastEscalation: Date | null = null;
  let escalationCount = 0;

  return {
    /**
     * POST /api/familiard/escalate
     * Receives escalation payloads from Familiard.
     */
    async escalate(c: any) {
      const payload = await c.req.json() as EscalationPayload;

      // Ensure escalation thread exists
      const threadId = deps.config.escalationThreadId || 'familiard-escalations';
      deps.ensureThread(threadId, ESCALATION_THREAD_TITLE);

      // Parse into message
      const msg = parseEscalation(payload, threadId);

      // Insert as pending user message (daemon will process it)
      deps.insertMessage(
        threadId,
        'user',
        msg.content,
        'pending',
        JSON.stringify({ source: 'familiard', priority: 'high', events: msg.events })
      );

      lastEscalation = new Date();
      escalationCount++;

      return c.json({ ok: true, escalationCount });
    },

    /**
     * GET /api/familiard/config
     * Returns generated config.yaml for Familiard setup.
     */
    getConfig(c: any) {
      return c.text(generateFamiliardConfig(deps.config));
    },

    /**
     * GET /api/familiard/status
     * Returns Familiard integration status.
     */
    getStatus(c: any) {
      return c.json({
        configured: true,
        lastEscalation: lastEscalation?.toISOString() || null,
        escalationCount,
        watchers: deps.config.watchers.length,
        model: deps.config.model || 'llama3.1:8b-instruct',
      });
    },
  };
}
