/**
 * Enterprise Model Router
 *
 * Routes each intelligence layer to its optimal model based on benchmark results.
 * Falls back to Claude Max when the cheap model fails.
 *
 * Usage:
 *   import { routedCall, routedToolCall } from './model-router.mjs';
 *   const response = await routedCall('compression', system, prompt);
 *   const toolCalls = await routedToolCall('extraction', system, prompt, tools);
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';

const CONFIG_PATH = join(homedir(), '.enterprise', 'model-config.json');
const OLLAMA_URL = 'http://localhost:11434';

// Load model config (generated by benchmark)
let modelConfig = {};
if (existsSync(CONFIG_PATH)) {
  try { modelConfig = JSON.parse(readFileSync(CONFIG_PATH, 'utf8')); } catch {}
}

// Default: Claude Max for everything
const DEFAULT = { provider: 'claude', model: 'claude-max' };

function getLayerConfig(layer) {
  return modelConfig[layer] || DEFAULT;
}

// ─── Provider Callers ───

function callOllama(model, prompt, timeout = 60000) {
  const body = JSON.stringify({ model, prompt, stream: false, options: { num_predict: 4096 } });
  try {
    const raw = execSync(
      `curl -s --max-time ${timeout/1000} -X POST ${OLLAMA_URL}/api/generate -d '${body.replace(/'/g, "'\\''")}'`,
      { encoding: 'utf8', timeout: timeout + 5000, maxBuffer: 10 * 1024 * 1024 }
    );
    return JSON.parse(raw).response || '';
  } catch { return null; }
}

function callClaude(prompt, timeout = 120000) {
  const escaped = prompt.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  try {
    return execSync(`claude --print -p "${escaped}"`, {
      encoding: 'utf8', timeout, maxBuffer: 10 * 1024 * 1024,
    }).trim();
  } catch { return null; }
}

function callOpenRouter(model, prompt, timeout = 30000) {
  const body = JSON.stringify({ model, messages: [{ role: 'user', content: prompt }], max_tokens: 4096 });
  try {
    const raw = execSync(
      `curl -s --max-time ${timeout/1000} -X POST https://openrouter.ai/api/v1/chat/completions -H "Content-Type: application/json" -d '${body.replace(/'/g, "'\\''")}'`,
      { encoding: 'utf8', timeout: timeout + 5000 }
    );
    return JSON.parse(raw).choices?.[0]?.message?.content || null;
  } catch { return null; }
}

function callProvider(config, prompt) {
  switch (config.provider) {
    case 'ollama': return callOllama(config.model, prompt);
    case 'openrouter': return callOpenRouter(config.model, prompt);
    case 'claude': return callClaude(prompt);
    default: return null;
  }
}

// ─── Routed Calls ───

/**
 * Call the optimal model for a layer, with fallback to Claude Max.
 */
export function routedCall(layer, system, prompt) {
  const config = getLayerConfig(layer);
  const fullPrompt = system ? `${system}\n\n---\n\n${prompt}` : prompt;

  // Try cheap model first
  if (config.provider !== 'claude') {
    const response = callProvider(config, fullPrompt);
    if (response && response.length > 10) {
      return { response, model: `${config.provider}/${config.model}`, fallback: false };
    }
    // Cheap model failed, fall back to Claude
  }

  const response = callClaude(fullPrompt);
  return { response: response || '', model: 'claude-max', fallback: config.provider !== 'claude' };
}

/**
 * Call for tool-call style responses (extraction, organization).
 * Asks the model to return JSON, parses the result.
 */
export function routedToolCall(layer, system, prompt, tools) {
  const toolDescs = tools.map(t =>
    `Tool: ${t.name}\n${t.description}\nParams: ${JSON.stringify(t.parameters)}`
  ).join('\n\n');

  const fullPrompt = `${system}\n\nTools:\n${toolDescs}\n\nRespond with a JSON array of tool calls: [{"name":"...","args":{...}}]\nOnly JSON, no other text.\n\n---\n\n${prompt}`;

  const config = getLayerConfig(layer);

  // Try cheap model
  if (config.provider !== 'claude') {
    const raw = callProvider(config, fullPrompt);
    if (raw) {
      const match = raw.match(/\[[\s\S]*\]/);
      if (match) {
        try {
          const calls = JSON.parse(match[0]);
          if (Array.isArray(calls) && calls.length > 0) {
            return { calls, model: `${config.provider}/${config.model}`, fallback: false };
          }
        } catch {}
      }
    }
  }

  // Fallback to Claude
  const escaped = fullPrompt.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  try {
    const raw = execSync(`claude --print -p "${escaped}"`, {
      encoding: 'utf8', timeout: 120000, maxBuffer: 10 * 1024 * 1024,
    }).trim();
    const match = raw.match(/\[[\s\S]*\]/);
    const calls = match ? JSON.parse(match[0]) : [];
    return { calls, model: 'claude-max', fallback: config.provider !== 'claude' };
  } catch {
    return { calls: [], model: 'claude-max-failed', fallback: true };
  }
}

/**
 * Get current routing config for display/logging.
 */
export function getRoutingConfig() {
  return {
    configPath: CONFIG_PATH,
    hasConfig: existsSync(CONFIG_PATH),
    layers: Object.fromEntries(
      ['extraction', 'organization', 'compression', 'synthesis', 'chat'].map(l => [l, getLayerConfig(l)])
    ),
  };
}
